name: theoplayer_platform_interface
description: A common platform interface for the THEOplayer Flutter SDK. Used by the platform-specific packages of `theoplayer`.
version: 7.3.1
homepage: https://theoplayer.com
repository: https://github.com/THEOplayer/flutter-theoplayer-sdk

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^12.0.0
  build_runner: ^2.4.6

topics:
  - theoplayer
  - video-player
  - video
  - dash
  - hls
