name: theoplayer
description: Official THEOplayer Flutter SDK that brings streaming video playback for Android, iOS, and Web platforms with DRM support and premium features.
version: 7.0.0
homepage: https://theoplayer.com
repository: https://github.com/THEOplayer/flutter-theoplayer-sdk

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  theoplayer_platform_interface: 7.0.0
  theoplayer_android: 7.0.0
  theoplayer_ios: 7.0.0
  theoplayer_web: 7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_theoplayer_sdk_android
      ios:
        default_package: flutter_theoplayer_sdk_ios
      web:
        default_package: flutter_theoplayer_sdk_web

topics:
  - theoplayer
  - video-player
  - video
  - dash
  - hls
