name: theoplayer
description: THEOplayer Flutter SDK
version: 1.0.0
homepage: https://theoplayer.com
repository: https://github.com/THEOplayer/flutter-theoplayer-sdk

environment:
  sdk: ^3.2.6
  flutter: ^3.16.9

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  theoplayer_platform_interface:
    path: ../flutter_theoplayer_sdk_platform_interface
  theoplayer_web:
    path: ../flutter_theoplayer_sdk_web
  theoplayer_android:
    path: ../flutter_theoplayer_sdk_android
  theoplayer_ios:
    path: ../flutter_theoplayer_sdk_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_theoplayer_sdk_android
      ios:
        default_package: flutter_theoplayer_sdk_ios
      web:
        default_package: flutter_theoplayer_sdk_web

topics:
  - theoplayer
  - video-player
  - video
  - dash
  - hls
