name: theoplayer_android
description: THEOplayer Flutter SDK Android
version: 1.0.0
homepage: https://theoplayer.com
repository: https://github.com/THEOplayer/flutter-theoplayer-sdk

environment:
  sdk: ^3.2.6
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  theoplayer_platform_interface: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: theoplayer
    platforms:
      android:
        package: com.theoplayer.flutter
        pluginClass: TheoplayerPlugin
        dartPluginClass: THEOplayerAndroid

topics:
  - theoplayer
  - video-player
  - video
  - dash
  - hls
