name: THEOplayerFlutterSDK

packages:
  - flutter_theoplayer_sdk_platform_interface
  - flutter_theoplayer_sdk_android
  - flutter_theoplayer_sdk_ios
  - flutter_theoplayer_sdk_web
  - flutter_theoplayer_sdk
  - flutter_theoplayer_sdk/example

scripts:
  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.