name: theoplayer
description: Official THEOplayer Flutter SDK that brings streaming video playback for Android, iOS, and Web platforms with DRM support and premium features.
version: 9.0.0
homepage: https://theoplayer.com
repository: https://github.com/THEOplayer/flutter-theoplayer-sdk

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  theoplayer_platform_interface: 9.0.0
  theoplayer_android: 9.0.0
  theoplayer_ios: 9.0.0
  theoplayer_web: 9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - theoplayer
  - video-player
  - video
  - dash
  - hls
