name: theoplayer_integration_google_ima_android
description: Google IMA integration for THEOplayer Flutter SDK on Android. Used by `theoplayer` to support streaming video playback on Android platforms.
version: 8.3.0
homepage: https://theoplayer.com
repository: https://github.com/THEOplayer/flutter-theoplayer-sdk

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  theoplayer_integration_google_ima_platform_interface: 8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: theoplayer_integration_google_ima
    platforms:
      android:
        package: com.theoplayer.flutter_integration_google_ima
        pluginClass: FlutterIntegrationGoogleImaPlugin
        dartPluginClass: MethodChannelFlutterIntegrationGoogleImaAndroid

topics:
  - theoplayer
  - video-player
  - video
  - dash
  - hls
