name: theoplayer_web
description: THEOplayer Flutter SDK Web used by `theoplayer` to support the Web platform.
version: 1.0.1
homepage: https://theoplayer.com
repository: https://github.com/THEOplayer/flutter-theoplayer-sdk

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: ^0.6.7
  theoplayer_platform_interface: 1.0.1
  web: ">=0.3.0 <0.6.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: TheoplayerWeb
        fileName: theoplayer_web.dart

topics:
  - theoplayer
  - video-player
  - video
  - dash
  - hls
