name: theoplayer_ios
description: THEOplayer Flutter SDK for iOS. Used by `theoplayer` to support streaming video playback on the iOS platform.
version: 8.0.0
homepage: https://theoplayer.com
repository: https://github.com/THEOplayer/flutter-theoplayer-sdk

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  theoplayer_platform_interface: 8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TheoplayerPlugin
        dartPluginClass: THEOplayerIOS

topics:
  - theoplayer
  - video-player
  - video
  - dash
  - hls
