name: Build on PRs
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Call platform actions
      run: |
        echo "TODO: we need to call the platform specific actions"
    
#TODO: call platform-specific actions (if needed)
