name: Build on PRs
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
        
    - name: Print flutter version
      run: flutter --version
      
    - name: Pub get
      run: flutter pub get
      working-directory: flutter_theoplayer_sdk
    
    - name: Run unit test
      run: flutter test
      working-directory: flutter_theoplayer_sdk
      
    # configure for emulator
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    
    - name: AVD cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-33
        
    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true' #check previous step output
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."
        
    - name: Run integration tests on emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: flutter test integration_test
        working-directory: flutter_theoplayer_sdk/example

    #- name: Run integration tests
    #  run: flutter test integration_test
    #  working-directory: flutter_theoplayer_sdk/example
        
    - name: Build APK
      run: flutter build apk
      working-directory: flutter_theoplayer_sdk/example

    - name: Build app bundle
      run: flutter build appbundle
      working-directory: flutter_theoplayer_sdk/example
      
    - name: Save APK to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: example_app.apk
        path: flutter_theoplayer_sdk/example/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 5
        
  build_ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path

    - name: Print flutter version
      run: flutter --version
      
    - name: Pub get
      run: flutter pub get
      working-directory: flutter_theoplayer_sdk
    
    - name: Run unit tests
      run: flutter test
      working-directory: flutter_theoplayer_sdk
      
    - name: Start iOS simulator
      uses: futureware-tech/simulator-action@v3
      with:
        model: 'iPhone 14'
        os_version: '>=16.0'

    - name: Run integration tests
      run: flutter test integration_test
      working-directory: flutter_theoplayer_sdk/example
      
    - name: Build iOS
      run: flutter build ios --release --no-codesign
      working-directory: flutter_theoplayer_sdk/example

  build_web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path

    - name: Print flutter version
      run: flutter --version
      
    - name: Pub get
      run: flutter pub get
      working-directory: flutter_theoplayer_sdk
    
    - name: Run test
      run: flutter test
      working-directory: flutter_theoplayer_sdk
      
    - name: Install Chrome Browser
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
      id: setup-chrome
      
    - name: Check Browser version
      run: |
        echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
        ${{ steps.setup-chrome.outputs.chrome-path }} --version

    - name: Install Chromedriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '114.0.5735.90'

    - name: ⏳ Delay
      run: |
        echo "Waiting for Chromedriver to start..."
        sleep 20

    - name: Start Chromedriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub --port=4444 --verbose &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: Check Chromedriver Version
      run: chromedriver -v
    
    - name: ⏳ Delay
      run: |
        echo "Waiting for Chromedriver to start..."
        sleep 15
    
    - name: Check Chromedriver Port
      run: |
        lsof -i :4444
        
    - name: Run integration tests
      run: |
        flutter config --enable-web
        flutter drive --driver=webdriver_integration_test/webdriver.dart --target=integration_test/plugin_integration_test.dart -d web-server --release --browser-name=chrome --driver-port=4444
      working-directory: flutter_theoplayer_sdk/example
    
    - name: Build Web
      run: flutter build web
      working-directory: flutter_theoplayer_sdk/example
        
    - name: Save WEB to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: flutter_theoplayer_sdk/example/build/web/
        retention-days: 5
    
