name: Build on PRs
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
        
    - name: Print flutter version
      run: flutter --version
      
    - name: Pub get
      run: flutter pub get
      working-directory: flutter_theoplayer_sdk
    
    - name: Run test
      run: flutter test
      working-directory: flutter_theoplayer_sdk
        
    - name: Build APK
      run: flutter build apk
      working-directory: flutter_theoplayer_sdk/example

    - name: Build app bundle
      run: flutter build appbundle
      working-directory: flutter_theoplayer_sdk/example
      
    - name: Save APK to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: example_app.apk
        path: flutter_theoplayer_sdk/example/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 5
        
  build_ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path

    - name: Print flutter version
      run: flutter --version
      
    - name: Pub get
      run: flutter pub get
      working-directory: flutter_theoplayer_sdk
    
    - name: Run test
      run: flutter test
      working-directory: flutter_theoplayer_sdk
      
    - name: Build iOS
      run: flutter build ios --release --no-codesign
      working-directory: flutter_theoplayer_sdk/example

  build_web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path

    - name: Print flutter version
      run: flutter --version
      
    - name: Pub get
      run: flutter pub get
      working-directory: flutter_theoplayer_sdk
    
    - name: Run test
      run: flutter test
      working-directory: flutter_theoplayer_sdk
      
    - name: Build Web
      run: flutter build web
      working-directory: flutter_theoplayer_sdk/example
      
    - name: Save WEB to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: flutter_theoplayer_sdk/example/build/web/
        retention-days: 5
